---
- name: variables from PLAY-1
  hosts: localhost
  vars:
    Course: "DevOps"
    Trainee: "Ravikumar"
    Duration: "110Hrs"
  tasks:
    - name: check variables
      ansible.builtin.debug:
        msg: "Hi, I am learning {{Course}}, Trainee is {{Trainee}},Duration is {{Duration}}"
